services:
  frontend:
    build:
      context: ./frontend
    ports:
      - '80:80'
    env_file:
      - .env.frontend
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
    ports:
      - '3000:3000'
    env_file:
      - .env.backend
