name: Build and Publish Docker Images

on:
  push:
    branches:
      - main
    paths:
      - 'frontend/**'
      - 'backend/**'

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        service: [frontend, backend]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Get commit SHA
      id: vars
      run: echo "SHA=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Check for ${{ matrix.service }} changes
      id: changes
      uses: dorny/paths-filter@v3
      with:
        filters: |
          service:
            - '${{ matrix.service }}/**'

    - name: Build and push ${{ matrix.service }} container
      if: steps.changes.outputs.service == 'true'
      uses: docker/build-push-action@v6
      with:
        platforms: linux/amd64,linux/arm64
        context: ./${{ matrix.service }}
        file: ./${{ matrix.service }}/Dockerfile
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/${{ matrix.service }}:${{ env.SHA }}
        cache-from: type=gha
        cache-to: type=gha,mode=max

    - name: Security scanning
      if: steps.changes.outputs.service == 'true'
      uses: docker/scout-action@v1
      with:
        command: quickview,cves,sbom
        image: ${{ secrets.DOCKER_USERNAME }}/${{ matrix.service }}:${{ env.SHA }}
